chowist/urls.py
from django.contrib import admin
from django.urls import include, path

# Default app
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("portal.urls")),
    path("places/", include("places.urls")),
]

places/urls.py
from django.urls import path

from places import views

app_name = "places"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("restaurants/", views.RestaurantListView.as_view(), name="restaurant-list"),
    path(
        "restaurants/<int:pk>/",
        views.RestaurantDetailView.as_view(),
        name="restaurant-detail",
    ),
    path(
        "restaurants/<int:pk>/update/",
        views.RestaurantUpdateView.as_view(),
        name="restaurant-update",
    ),
    path(
        "restaurants/random/",
        views.RestaurantRandomView.as_view(),
        name="restaurant-random",
    ),
    path(
        "restaurants/<int:restaurant_id>/review/",
        views.RestaurantReviewView.as_view(),
        name="restaurant-review",
    ),
]

portal/urls.py
from django.urls import path

from portal import views

app_name = "portal"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("signup/", views.ProfileSignupView.as_view(), name="signup"),
    path("profile/", views.ProfileDetailView.as_view(), name="profile"),
    path("profile/update/", views.ProfileUpdateView.as_view(), name="profile-update"),
]

ratings/urls.py
from django.urls import path

from ratings import views

# Insert your urls here.

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('restaurants/', views.RestaurantListView.as_view(), name='restaurant_list'),
]

ratings/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.list import ListView

from ratings.models import Restaurant

# Create your views here.

class HomeView(TemplateView):
    template_name = 'ratings/home.html'


class RestaurantListView(ListView):
    model = Restaurant

ratings/templates/ratings/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  {% block meta %}
  {% endblock %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/sticky-footer-navbar.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'portal:home' %}">chowist</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'portal:home' %}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'ratings:home' %}">Ratings</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <main role="main">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="footer">
    <div class="container">
      <span class="text-muted">&copy; 2014-2018 <a href="https://huangsam.github.io">@huangsam</a></p>
    </div>
  </footer>
  <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ratings/templates/ratings/home.html
{% extends 'ratings/base.html' %}

{% block meta %}
<title>Welcome to ratings!</title>
{% endblock %}

{% block content %}
<div class="container lead-container">
  <h1>Ratings</h1>
  <p class="lead">Find ratings for the places you love.</p>
  <p>There are so many restaurants all over the Bay Area! However, we are currently keeping the list down to 10-100 restaurants so that you don't get overwhelmed by all the choices out there. And so that you can focus on your work.</p>
  <p><a href="#">Click here</a> for an aggregate view. Each restaurant should also have an associated detailed view.</p>
</div>
{% endblock %}

ratings/templates/ratings/restaurant_list.html
{% extends 'ratings/base.html' %}

{% block meta %}
<title>Ratings</title>
{% endblock %}

{% block content %}
<div class="container lead-container pb-1">
  <h1>All Restaurants</h1>
  <p>The restaurants listed so far:</p>
  <ul>
  {% for restaurant in object_list %}
    <li>{{ restaurant.name }}</li>
  {% empty %}
    <li>No restaurants yet.</li>
  {% endfor %}
  </ul>
</div>
{% endblock %}